In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from scipy.io import loadmat

%matplotlib inline

In [2]:
### Reading all files
path = 'data/david_20200123_session1_0'
ext = '.mat'
data = pd.DataFrame()
for i in range(1, 7):
    filename = path + str(i) + ext
    file_data = loadmat(filename)
    mdata = file_data['data']
    temp = pd.DataFrame(mdata)
    data = pd.concat([data, temp])
data.shape

(1170432, 73)

In [3]:
cols = np.arange(73)
columns = []
[columns.append(str(x)) for x in cols]
columns

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72']

In [4]:
data = data.values
df = pd.DataFrame(data, columns=columns)
df

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
0,17.105981,24.554888,15.005356,12.292314,15.023244,18.086515,20.015809,14.553146,13.430839,7.616764,...,-5.800183,2.146358,-10.774213,0.102805,-0.498674,-0.264332,-0.534325,0.538818,0.140796,0.0
1,19.296642,25.934498,16.174868,14.147057,15.824592,18.721176,20.827001,12.537479,12.982798,7.100069,...,-3.546706,5.790218,-8.863672,0.140478,-0.377666,-0.064091,-0.349212,0.645850,0.633520,0.0
2,21.258317,27.142551,17.208273,15.722504,16.394587,19.218464,21.415916,10.801487,12.409850,6.527207,...,-1.539948,8.929023,-7.180271,0.171621,-0.258195,0.123417,-0.173290,0.739186,1.073237,0.0
3,22.788739,28.009005,17.972828,16.786124,16.550509,19.432372,21.545947,9.363138,11.577936,5.851425,...,0.022522,11.243235,-5.915357,0.192651,-0.156389,0.276135,-0.032065,0.817128,1.420439,0.0
4,23.763603,28.410634,18.393665,17.216624,16.218170,19.279510,21.136680,8.262744,10.453829,5.081501,...,1.065431,12.660267,-5.114605,0.200139,-0.075091,0.388460,0.063033,0.875565,1.660915,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170427,17.572778,29.569014,12.968514,11.675471,18.034716,26.043895,46.305481,46.706776,29.776484,15.277962,...,-13.589682,72.806457,-44.930659,1.236395,1.173870,0.461537,0.746300,0.504873,1.375933,0.0
1170428,15.395215,26.226632,11.247746,10.312256,15.984565,22.948378,40.540566,39.978270,26.723418,13.345318,...,-11.499908,71.470267,-42.561739,1.093431,1.097120,0.397797,0.676303,0.467839,1.290587,0.0
1170429,12.861069,22.123910,9.284959,8.632709,13.423864,19.146815,33.625252,32.214256,22.688050,11.061853,...,-9.150135,65.966284,-38.173789,0.915296,0.960552,0.331843,0.591653,0.409633,1.145428,0.0
1170430,10.056843,17.430176,7.175525,6.738043,10.508577,14.896093,26.023543,24.160096,17.921958,8.563782,...,-6.772096,55.934591,-31.685116,0.712974,0.774847,0.261649,0.485064,0.332250,0.941185,0.0
1170431,7.152962,12.472116,5.047819,4.772186,7.456699,10.519299,18.329972,16.504727,12.794056,6.018346,...,-4.576087,42.460967,-23.616934,0.504615,0.564413,0.188416,0.361391,0.243299,0.697295,0.0

In [5]:
df = df.drop(['67','68','69','70','71'], axis=1)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,58,59,60,61,62,63,64,65,66,72
0,17.105981,24.554888,15.005356,12.292314,15.023244,18.086515,20.015809,14.553146,13.430839,7.616764,...,-8.754141,-15.292612,-14.702328,-9.591363,-6.502740,-5.800183,2.146358,-10.774213,0.102805,0.0
1,19.296642,25.934498,16.174868,14.147057,15.824592,18.721176,20.827001,12.537479,12.982798,7.100069,...,-6.756346,-12.365625,-12.139328,-7.196754,-4.378569,-3.546706,5.790218,-8.863672,0.140478,0.0
2,21.258317,27.142551,17.208273,15.722504,16.394587,19.218464,21.415916,10.801487,12.409850,6.527207,...,-4.926926,-9.776067,-9.946174,-5.021252,-2.459225,-1.539948,8.929023,-7.180271,0.171621,0.0
3,22.788739,28.009005,17.972828,16.786124,16.550509,19.432372,21.545947,9.363138,11.577936,5.851425,...,-3.425621,-7.784500,-8.359430,-3.257660,-0.929891,0.022522,11.243235,-5.915357,0.192651,0.0
4,23.763603,28.410634,18.393665,17.216624,16.218170,19.279510,21.136680,8.262744,10.453829,5.081501,...,-2.330924,-6.486737,-7.469046,-1.991829,0.127604,1.065431,12.660267,-5.114605,0.200139,0.0

In [6]:
columns.remove('67')
columns.remove('68')
columns.remove('69')
columns.remove('70')
columns.remove('71')

In [7]:
sfreq = 512
trigger_points = {1:6, 2:4, 3:2, 4:2 }
asynch_label = []
real_label = []
i = 0
while i < len(df['72']):
    if(df['72'][i] == 1):
        end = (sfreq * trigger_points[1]) + 1
        for j in range(i, i+end):
            real_label.append(1)
            asynch_label.append(1)
        i += end
    elif(df['72'][i] == 2):
        end = (sfreq * trigger_points[2]) + 1
        for j in range(i, i+end):
            real_label.append(2)
            asynch_label.append(1)
        i += end
    elif(df['72'][i] == 3):
        end = (sfreq * trigger_points[3]) + 1
        for j in range(i, i+end):
            real_label.append(3)
            asynch_label.append(1)
        i += end
    elif(df['72'][i] == 4):
        end = (sfreq * trigger_points[4]) + 1
        for j in range(i, i+end):
            real_label.append(4)
            asynch_label.append(4)
        i += end
    elif(df['72'][i] == 0):
        real_label.append(0)
        asynch_label.append(0)
        i += 1

In [8]:
df['asynch_label'] = asynch_label

In [9]:
asynch_label = np.array(asynch_label)
real_label = np.array(real_label)

In [10]:
unique = {1: 0, 4: 0}
count1 = 0
count4 = 0
for i in asynch_label:
    if i == 1:
        count1 += 1
    if i == 4:
        count4 += 1
unique[1] = count1
unique[4] = count4
print(unique)

{1: 276615, 4: 46125}

In [11]:
type(df.iloc[0:1024, :64].T.values)
print(df.iloc[0:1024, :64].values)
print(df.iloc[0:1024, :64].T.values)

[[ 17.10598073  24.55488849  15.00535623 ...  -9.59136272  -6.50273959
   -5.80018346]
 [ 19.29664243  25.93449812  16.17486787 ...  -7.19675379  -4.37856937
   -3.5467065 ]
 [ 21.2583171   27.14255094  17.20827251 ...  -5.02125221  -2.45922502
   -1.5399477 ]
 ...
 [ -8.75881683 -15.23505869 -10.8952061  ...   1.77667416 -11.47691409
   -2.86122895]
 [ -9.63925452 -15.45773382 -11.60252514 ...   2.42367363 -10.97477846
   -2.20168484]
 [-10.27262823 -15.42506761 -12.03961674 ...   3.24840638 -10.42066624
   -1.40439644]]
[[ 17.10598073  19.29664243  21.2583171  ...  -8.75881683  -9.63925452
  -10.27262823]
 [ 24.55488849  25.93449812  27.14255094 ... -15.23505869 -15.45773382
  -15.42506761]
 [ 15.00535623  16.17486787  17.20827251 ... -10.8952061  -11.60252514
  -12.03961674]
 ...
 [ -9.59136272  -7.19675379  -5.02125221 ...   1.77667416   2.42367363
    3.24840638]
 [ -6.50273959  -4.37856937  -2.45922502 ... -11.47691409 -10.97477846
  -10.42066624]
 [ -5.80018346  -3.5467065   -1.5399477  ...  -2.86122895  -2.20168484
   -1.40439644]]

In [12]:
def data_win(sfreq, data, asynch_label, real_label):
    sampling_window = 2 * sfreq
    shift_length = 1 * sfreq
    t_start = 0
    
    new_data = []
    labels = []
    real = []


    while t_start + sampling_window < data.shape[0]:
        new_data.append(data.iloc[t_start:t_start+sampling_window, :64].T.values)
        labels.append(asynch_label[t_start:t_start+sampling_window])
        real.append(real_label[t_start:t_start+sampling_window])
        #labels.append(data.iloc[t_start:t_start+sampling_window, -1].values)
    
        t_start = t_start + shift_length
    
    return np.array(new_data), np.array(labels), np.array(real)

In [13]:
data_new, label_new, real = data_win(sfreq, df, asynch_label, real_label)

In [14]:
data_new.shape
## shape is 3D
## number of sequences, window_size (timestep), features(channels)

(2591, 64, 1024)

In [15]:
label_new.shape

(2591, 1024)

In [16]:
label_new

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
#### Converting label to shape (2591, 1)
label = []

for i in label_new:
    count1 = np.count_nonzero(i==1)
    count4 = np.count_nonzero(i==4)
    if count1 >= 512:
        to_add = 1
    elif count4 >= 512:
        to_add = 4
    else:
        to_add = 0
    label.append(to_add)
    
label = np.array(label)

label_4 = []
for i in real:
    count1 = np.count_nonzero(i==1)
    count2 = np.count_nonzero(i==2)
    count3 = np.count_nonzero(i==3)
    count4 = np.count_nonzero(i==4)
    if count1 >= 512:
        to_add = 1
    elif count2 >= 512:
        to_add = 2
    elif count3 >= 512:
        to_add = 3
    elif count4 > 512:
        to_add = 4
    else:
        to_add = 0
    label_4.append(to_add)
    
label_4= np.array(label_4)

In [18]:
data_new.shape

train_data = []
label_data = []
real_label_data = []

for i in range(len(label)):
    if label[i] != 0:
        label_data.append(label[i])
        train_data.append(data_new[i])
        real_label_data.append(label_4[i])
label_data = np.array(label_data)
train_data = np.array(train_data)
real_label_data = np.array(real_label_data)

In [19]:
print(label_data.shape)
print(train_data.shape)
print(real_label_data.shape)

(631,)
(631, 64, 1024)
(631,)

In [20]:
print(label_data)
print(real_label_data)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 4 4 4 4 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1
 1 1 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 4
 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1
 1 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 4 4
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 4 4 4 4 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 4 4 1 1 1 1 4 4 1 1 1 1 1 1 1 1 1 1 1 1 4 4 1 1 1 1 1 1 1 1
 1 1]
[3 3 1 1 1 1 1 1 3 3 2 2 2 2 2 2 2 2 4 4 1 1 1 1 1 1 2 2 2 2 3 3 1 1 1 1 1
 1 4 4 4 4 1 1 1 1 1 1 3 3 3 3 4 4 2 2 2 2 2 2 2 2 3 3 1 1 1 1 1 1 4 4 1 1
 1 1 1 1 2 2 2 2 4 4 4 4 3 3 1 1 1 1 1 1 2 2 2 2 3 3 1 1 1 1 1 1 4 4 3 3 4
 4 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 2 2 2 2 2 2
 2 2 3 3 2 2 2 2 4 4 3 3 1 1 1 1 1 1 3 3 3 3 1 1 1 1 1 1 4 4 3 3 2 2 2 2 2
 2 2 2 3 3 1 1 1 1 1 1 2 2 2 2 4 4 1 1 1 1 1 1 4 4 4 4 2 2 2 2 1 1 1 1 1 1
 1 1 1 1 1 1 3 3 3 3 3 1 1 1 1 1 1 2 2 2 2 4 4 3 3 2 2 2 2 4 4 1 1 1 1 1 1
 3 3 1 1 1 1 1 1 2 2 2 2 3 3 2 2 2 2 3 3 4 4 1 1 1 1 1 1 4 4 4 4 2 2 2 2 1
 1 1 1 1 1 3 3 3 3 4 4 2 2 2 2 4 4 1 1 1 1 1 1 3 3 2 2 2 2 4 4 1 1 1 1 1 1
 2 2 2 2 1 1 1 1 1 1 3 3 3 3 4 4 2 2 2 2 2 2 2 2 3 3 1 1 1 1 1 1 4 4 1 1 1
 1 1 1 2 2 2 2 4 4 4 4 3 3 1 1 1 1 1 1 2 2 2 2 3 3 1 1 1 1 1 1 4 4 3 3 4 4
 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 2 2 2 2 2 2 2
 2 3 3 2 2 2 2 4 4 3 3 1 1 1 1 1 1 3 3 3 3 1 1 1 1 1 1 4 4 3 3 2 2 2 2 2 2
 2 2 3 3 1 1 1 1 1 1 2 2 2 2 4 4 1 1 1 1 1 1 4 4 4 4 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 3 3 3 3 1 1 1 1 1 1 2 2 2 2 4 4 3 3 2 2 2 2 4 4 1 1 1 1 1 1 3 3
 1 1 1 1 1 1 2 2 2 2 3 3 2 2 2 2 3 3 4 4 1 1 1 1 1 1 4 4 4 4 2 2 2 2 1 1 1
 1 1 1 3 3 3 3 4 4 2 2 2 2 4 4 1 1 1 1 1 1 3 3 2 2 2 2 4 4 1 1 1 1 1 1 2 2
 2 2]

Splitting this data into train and test split. And applying CSP

In [21]:
event_dict = {'Hands': 1, 'Relax': 4}

In [22]:
### Actual epoched data stores data as (No. of events, no. of channels, no of times)

In [23]:
import mne
from mne.decoding import CSP

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(train_data, label_data, test_size=0.2, random_state=42)
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(train_data, real_label_data, test_size=0.2, random_state=42)

In [26]:
print(X_train_2.shape)
print(X_train_4.shape)
print(np.array_equal(X_train_2, X_train_4))

print(X_test_2.shape)
print(X_test_4.shape)
print(np.array_equal(X_test_2, X_test_4))

(504, 64, 1024)
(504, 64, 1024)
True
(127, 64, 1024)
(127, 64, 1024)
True

In [27]:
csp = CSP(n_components=4, reg=None, log=True, norm_trace=False)

In [28]:
X_train_csp = csp.fit_transform(X_train_2, y_train_2)

Computing data rank from raw with rank=None
    Using tolerance 3.2e+02 (2.2e-16 eps * 64 dim * 2.2e+16  max singular value)
    Estimated rank (mag): 64
    MAG: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating covariance using EMPIRICAL
Done.
Computing data rank from raw with rank=None
    Using tolerance 1.5e+02 (2.2e-16 eps * 64 dim * 1e+16  max singular value)
    Estimated rank (mag): 64
    MAG: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating covariance using EMPIRICAL
Done.

In [29]:
X_test_csp = csp.transform(X_test_2)

In [30]:
from sklearn.svm import SVC
# from sklearn.model_selection import GridSearchCV

In [38]:
# param = {'C' : [ 0.1, 1, 10, 50, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf', 'linear']}
svm = SVC()

In [39]:
# grid = GridSearchCV(svm, param, cv=10, scoring='accuracy', return_train_score=True, verbose=1)

In [40]:
# grid.fit(X_train_csp, y_train)
svm.fit(X_train_csp, y_train_2)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [41]:
# print(grid.best_params_)
# print(grid.best_estimator_)

In [42]:
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score

In [43]:
y_pred = svm.predict(X_test_csp)

In [44]:
print('Accuracy: ', accuracy_score(y_test_2, y_pred))
print('Cohen Kappa: ', cohen_kappa_score(y_test_2, y_pred))

Accuracy:  0.937007874015748
Cohen Kappa:  0.6342692584593232

In [66]:
queue = [0] * 6
predicted_y = []
counter = 0
for i in X_test_csp:
    value = svm.predict([i])
    queue.append(value[0])
    queue.pop(0)
    count1 = queue.count(1)
    percentage_count = (count1 * 100) / len(queue)
    if(percentage_count <= 25):
        class_value = 3
    elif(25 < percentage_count <= 50):
        class_value = 2
    elif(50 < percentage_count):
        class_value = 1
        counter += 1
        if(counter > 2):
            queue = [0] * 8
            counter = 0
    if(value == 4):
        queue = [0] * 8
        predicted_y.append(value[0])
    else:
        predicted_y.append(class_value)
        
predicted_y = np.array(predicted_y)

In [67]:
print(y_test_4)
# print(y_test_2)
print(predicted_y)
print(accuracy_score(y_test_4, predicted_y))
print(cohen_kappa_score(y_test_4, predicted_y))

[2 3 1 2 4 1 1 1 1 1 2 3 2 1 1 1 1 4 2 2 1 2 3 2 3 4 1 2 1 3 3 3 1 2 1 2 1
 2 2 3 1 4 3 3 1 4 1 1 2 2 4 2 2 2 3 2 1 1 2 3 2 1 4 4 2 2 2 2 3 3 1 1 4 2
 3 2 1 4 4 2 1 2 2 2 2 4 1 1 4 1 4 1 2 1 1 1 3 3 1 1 1 2 2 1 4 2 2 3 2 1 3
 1 1 2 2 2 1 1 2 1 1 2 3 1 2 2 3]
[3 2 2 1 4 3 3 2 2 1 3 3 2 2 1 1 1 4 3 3 2 2 1 1 1 4 3 3 2 2 4 3 3 2 2 1 1
 1 3 3 2 2 1 1 1 4 3 3 2 2 4 3 3 2 2 1 1 1 3 3 2 2 1 1 1 3 3 2 2 1 1 1 4 3
 3 2 2 1 1 1 3 3 2 2 1 4 3 3 2 2 4 3 3 2 2 1 3 3 2 2 1 1 1 3 3 2 2 1 1 1 3
 3 2 2 1 1 1 3 3 2 2 1 1 1 3 3 2]
0.3543307086614173
0.10069084628670122