In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from scipy.io import loadmat

%matplotlib inline

In [2]:
### Reading all files
path = 'data/david_20200123_session1_0'
ext = '.mat'
data = pd.DataFrame()
for i in range(1, 9):
    filename = path + str(i) + ext
    file_data = loadmat(filename)
    mdata = file_data['data']
    temp = pd.DataFrame(mdata)
    data = pd.concat([data, temp])
data.shape

(1327616, 73)

In [3]:
cols = np.arange(73)
columns = []
[columns.append(str(x)) for x in cols]
columns

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72']

In [4]:
data = data.values
df = pd.DataFrame(data, columns=columns)
df

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
0,17.105981,24.554888,15.005356,12.292314,15.023244,18.086515,20.015809,14.553146,13.430839,7.616764,...,-5.800183,2.146358,-10.774213,0.102805,-0.498674,-0.264332,-0.534325,0.538818,0.140796,0.0
1,19.296642,25.934498,16.174868,14.147057,15.824592,18.721176,20.827001,12.537479,12.982798,7.100069,...,-3.546706,5.790218,-8.863672,0.140478,-0.377666,-0.064091,-0.349212,0.645850,0.633520,0.0
2,21.258317,27.142551,17.208273,15.722504,16.394587,19.218464,21.415916,10.801487,12.409850,6.527207,...,-1.539948,8.929023,-7.180271,0.171621,-0.258195,0.123417,-0.173290,0.739186,1.073237,0.0
3,22.788739,28.009005,17.972828,16.786124,16.550509,19.432372,21.545947,9.363138,11.577936,5.851425,...,0.022522,11.243235,-5.915357,0.192651,-0.156389,0.276135,-0.032065,0.817128,1.420439,0.0
4,23.763603,28.410634,18.393665,17.216624,16.218170,19.279510,21.136680,8.262744,10.453829,5.081501,...,1.065431,12.660267,-5.114605,0.200139,-0.075091,0.388460,0.063033,0.875565,1.660915,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327611,-66.688258,-12.307188,6.200398,6.713645,26.443862,53.734263,-23.031884,-9.919421,-0.900873,4.893628,...,8.068660,-22.303417,20.965594,0.150515,-0.137253,0.217990,1.469553,-0.322774,-0.247915,0.0
1327612,-59.679293,-7.392134,10.097233,9.175118,28.737415,55.776481,-21.219983,-8.217550,0.856960,6.753870,...,7.153815,-19.679470,21.734531,0.176543,-0.169279,0.201896,1.328606,-0.297509,-0.254054,0.0
1327613,-50.321061,-3.272886,12.209575,10.273262,28.315367,53.052786,-18.629474,-6.108225,2.528853,7.703075,...,5.971714,-16.668663,20.396376,0.191061,-0.175749,0.173334,1.139413,-0.261790,-0.242962,0.0
1327614,-39.345865,-0.439879,12.166012,9.813604,25.023053,45.651088,-15.192135,-4.035359,3.534407,7.504882,...,4.616818,-13.270640,17.231081,0.183602,-0.158473,0.136688,0.909249,-0.214320,-0.211883,0.0
1327615,-28.025480,0.891683,10.181824,8.013972,19.467663,34.832456,-11.208709,-2.453881,3.466980,6.203429,...,3.244393,-9.608006,12.953453,0.151820,-0.124382,0.096455,0.656874,-0.158473,-0.163945,0.0

In [5]:
df = df.drop(['67','68','69','70','71'], axis=1)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,58,59,60,61,62,63,64,65,66,72
0,17.105981,24.554888,15.005356,12.292314,15.023244,18.086515,20.015809,14.553146,13.430839,7.616764,...,-8.754141,-15.292612,-14.702328,-9.591363,-6.502740,-5.800183,2.146358,-10.774213,0.102805,0.0
1,19.296642,25.934498,16.174868,14.147057,15.824592,18.721176,20.827001,12.537479,12.982798,7.100069,...,-6.756346,-12.365625,-12.139328,-7.196754,-4.378569,-3.546706,5.790218,-8.863672,0.140478,0.0
2,21.258317,27.142551,17.208273,15.722504,16.394587,19.218464,21.415916,10.801487,12.409850,6.527207,...,-4.926926,-9.776067,-9.946174,-5.021252,-2.459225,-1.539948,8.929023,-7.180271,0.171621,0.0
3,22.788739,28.009005,17.972828,16.786124,16.550509,19.432372,21.545947,9.363138,11.577936,5.851425,...,-3.425621,-7.784500,-8.359430,-3.257660,-0.929891,0.022522,11.243235,-5.915357,0.192651,0.0
4,23.763603,28.410634,18.393665,17.216624,16.218170,19.279510,21.136680,8.262744,10.453829,5.081501,...,-2.330924,-6.486737,-7.469046,-1.991829,0.127604,1.065431,12.660267,-5.114605,0.200139,0.0

In [6]:
columns.remove('67')
columns.remove('68')
columns.remove('69')
columns.remove('70')
columns.remove('71')

In [ ]:
sfreq = 512
trigger_points = {1:2, 2:2, 3:2, 4:2 }
asynch_label = []
i = 0
while i < len(df['72']):
    if(df['72'][i] == 1):
        end = (sfreq * trigger_points[1]) + 1
        for j in range(i, i+end):
            asynch_label.append(1)
        i += end
    elif(df['72'][i] == 2):
        end = (sfreq * trigger_points[2]) + 1
        for j in range(i, i+end):
            asynch_label.append(2)
        i += end
    elif(df['72'][i] == 3):
        end = (sfreq * trigger_points[3]) + 1
        for j in range(i, i+end):
            asynch_label.append(3)
        i += end
    elif(df['72'][i] == 4):
        end = (sfreq * trigger_points[4]) + 1
        for j in range(i, i+end):
            asynch_label.append(4)
        i += end
    elif(df['72'][i] == 0):
        asynch_label.append(0)
        i += 1

In [ ]:
df['asynch_label'] = asynch_label

In [ ]:
asynch_label = np.array(asynch_label)

In [ ]:
def data_win(sfreq, data, asynch_label):
    sampling_window = 2 * sfreq
    shift_length = 1 * sfreq
    t_start = 0
    
    new_data = []
    labels = []


    while t_start + sampling_window < data.shape[0]:
        new_data.append(data.iloc[t_start:t_start+sampling_window, :64].T.values)
        labels.append(asynch_label[t_start:t_start+sampling_window])
        #labels.append(data.iloc[t_start:t_start+sampling_window, -1].values)
    
        t_start = t_start + shift_length
    
    return np.array(new_data), np.array(labels)

In [ ]:
data_new, label_new = data_win(sfreq, df, asynch_label)

In [ ]:
#### Converting label to shape (2591, 1)
label = []

for i in label_new:
    count1 = np.count_nonzero(i==1)
    count4 = np.count_nonzero(i==4)
    if count1 > 512:
        to_add = 1
    elif count4 > 512:
        to_add = 4
    else:
        to_add = 0
    label.append(to_add)
    
label = np.array(label)

In [ ]:
data_new.shape

train_data = []
label_data = []

for i in range(len(label)):
    if label[i] != 0:
        label_data.append(label[i])
        train_data.append(data_new[i])
label_data = np.array(label_data)
train_data = np.array(train_data)

In [ ]:
print(label_data.shape)
print(train_data.shape)

In [ ]:
event_dict = {'L_Hands': 1, 'M_Hands': 2, 'S_Hands': 3, 'Relax': 4}

In [ ]:
import mne
from mne.decoding import CSP
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(train_data, label_data, test_size=0.2, random_state=42)

In [ ]:
csp = CSP(n_components=4, reg=None, log=True, norm_trace=False)

In [19]:
X_train_csp = csp.fit_transform(X_train, y_train)

Computing data rank from raw with rank=None
    Using tolerance 1.5e+02 (2.2e-16 eps * 64 dim * 1e+16  max singular value)
    Estimated rank (mag): 64
    MAG: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating covariance using EMPIRICAL
Done.
Computing data rank from raw with rank=None
    Using tolerance 1.4e+02 (2.2e-16 eps * 64 dim * 9.7e+15  max singular value)
    Estimated rank (mag): 64
    MAG: rank 64 computed from 64 data channels with 0 projectors
Reducing data rank from 64 -> 64
Estimating covariance using EMPIRICAL
Done.

In [20]:
X_test_csp = csp.transform(X_test)

In [21]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train_csp, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [22]:
from sklearn.metrics import accuracy_score, f1_score, cohen_kappa_score
y_pred = svm.predict(X_test_csp)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Cohen Kappa: ', cohen_kappa_score(y_test, y_pred))

Accuracy:  0.8611111111111112
Cohen Kappa:  0.7222222222222222